azure:
  keyvault:
    uri: ${AZURE_KEYVAULT_URI}
    client-id: ${AZURE_KEYVAULT_CLIENT_ID}
    client-key: ${AZURE_KEYVAULT_CLIENT_KEY}
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_SALT} # 加密/解密SALT(盐)
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      pool-name: AZURE_KEY_VAULT_DEMO # 任意值
logging:
  level:
    root: WARN
    org:
      wanjune:
        azure:
          keyvault:
            mapper: TRACE
