azure:
  keyvault:
    uri: ${BASE_URI}
    client-id: ${CLIENT_ID}
    client-key: ${CLIENT_SECRET}
jasypt:
  encryptor:
    password: ${ENCRYPT_SALT} # 加密/解密SALT(盐)
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      pool-name: AZURE_KEY_VAULT_DEMO # 任意值
logging:
  level:
    root: WARN
    org:
      wanjune:
        azure:
          keyvault:
            mapper: TRACE
